import Head from "next/head";
import { ChangeEvent, KeyboardEvent, useState } from "react";
import Todo from "~/components/diy/todo";
import { UserNav } from "~/components/diy/userNav";
import { Input } from "~/components/ui/input";
import { api } from "~/utils/api";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create T3 App-TodoList</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <AuthShowcase />
      </main>
    </>
  );
}

function AuthShowcase() {
  const { data, isLoading, isError, refetch } = api.todo.all.useQuery();
  const { mutateAsync } = api.todo.create.useMutation();

  const [newTodo, setNewTodo] = useState("");

  const handleInputChange = (e: ChangeEvent<HTMLInputElement>) => {
    setNewTodo(e.target.value);
  };

  if (isLoading) {
    return (
      <div className="mx-auto mt-5 flex w-1/3 justify-center">
        Loading Todos ....
      </div>
    );
  }

  if (isError) {
    return (
      <div className="mx-auto mt-5 flex w-1/3 justify-center">
        Loading Todos Error !!!
      </div>
    );
  }

  const handleConfirmCreate = async (e: KeyboardEvent<HTMLInputElement>) => {
    if (e.keyCode === 13) {
      await mutateAsync({ text: newTodo });
      await refetch();
      setNewTodo('');
    }
  };

  return (
    <>
      <div className="mx-auto mt-5 flex w-1/3 justify-end">
        <UserNav />
      </div>
      <div className="mx-auto my-5 flex w-1/3 flex-col justify-end">
        <div className="mb-2">
          {data.map((todo) => (
            <Todo todo={todo} />
          ))}
        </div>
        <Input
          placeholder="create new todo"
          value={newTodo}
          onChange={handleInputChange}
          onKeyDown={handleConfirmCreate}
        />
      </div>
    </>
  );
}
