import type { Todo as TodoType } from "@prisma/client";
import { signIn, useSession } from "next-auth/react";
import Head from "next/head";
import type { ChangeEvent, KeyboardEvent } from "react";
import { useState } from "react";
import Todo from "~/components/diy/todo";
import { UserNav } from "~/components/diy/userNav";
import { Button } from "~/components/ui/button";
import { Input } from "~/components/ui/input";
import { useToast } from "~/components/ui/use-toast";
import { api } from "~/utils/api";

export default function Home() {
  const { data } = useSession();

  return (
    <>
      <Head>
        <title>Create T3 App-TodoList</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        {data ? (
          <AuthShowcase />
        ) : (
          <div className="flex justify-center">
            <Button onClick={() => signIn()}>Sign In</Button>
          </div>
        )}
      </main>
    </>
  );
}

function AuthShowcase() {
  const { data, isLoading, isError, refetch } = api.todo.all.useQuery();
  const createMutation = api.todo.create.useMutation();
  const toggleMutation = api.todo.toggle.useMutation();

  const [newTodo, setNewTodo] = useState("");

  const { toast } = useToast();

  const handleInputChange = (e: ChangeEvent<HTMLInputElement>) => {
    setNewTodo(e.target.value);
  };

  if (isLoading) {
    return (
      <div className="mx-auto mt-5 flex w-1/3 justify-center">
        Loading Todos ....
      </div>
    );
  }

  if (isError) {
    return (
      <div className="mx-auto mt-5 flex w-1/3 justify-center">
        Loading Todos Error !!!
      </div>
    );
  }

  const handleConfirmCreate = async (e: KeyboardEvent<HTMLInputElement>) => {
    if (e.keyCode === 13) {
      if (newTodo === "") {
        toast({
          variant: "destructive",
          title: "Tips",
          description: "todo text empty!!",
        });
        return;
      }
      await createMutation.mutateAsync({ text: newTodo });
      await refetch();
      setNewTodo("");
    }
  };

  const handleToggle = async (todo: TodoType) => {
    await toggleMutation.mutateAsync({ id: todo.id, done: !todo.done });
    await refetch();
  };

  return (
    <>
      <div className="mx-auto mt-5 flex w-1/3 justify-end">
        <UserNav />
      </div>
      <div className="mx-auto my-5 flex w-1/3 flex-col justify-end">
        <div className="mb-2">
          {data.map((todo) => (
            <Todo todo={todo} key={todo.id} toggle={handleToggle} />
          ))}
        </div>
        <Input
          placeholder="create new todo"
          value={newTodo}
          onChange={handleInputChange}
          onKeyDown={handleConfirmCreate}
        />
      </div>
    </>
  );
}
