import { signIn, signOut, useSession } from "next-auth/react";
import Head from "next/head";
import { UserNav } from "~/components/diy/userNav";

import {
  Button
} from "~/components/ui/button";


import { api } from "~/utils/api";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create T3 App-TodoList</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <AuthShowcase />
      </main>
    </>
  );
}

function AuthShowcase() {
  const { data: sessionData } = useSession();

  return (
    <div className="flex flex-col items-center justify-end gap-4">
      <UserNav />
    </div>
  );
}
